title: Bugs-Dev
author: Y.B.kim
email: ybkim@bugs.co.kr
description: > # this means to ignore newlines until "show_exerpts:"
  벅스 개발자 허브
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: #여기 공백

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Bugs Development
  tagline: Web, API
  date_format: "%b %-d, %Y"
  style: red
  showNav: false
  showPicker: false
  disqus_shortname: https-bugs-dev-github-io-1

  # generate social links in footer
  #social_links:
  #  twitter: thelehhman
  #  github:  thelehhman
  #  linkedIn: in/thelehhman
  #  rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
